{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:48.708985Z",
     "start_time": "2020-11-12T22:50:48.703068Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
      "env: CUDA_VISIBLE_DEVICES=0\n"
     ]
    }
   ],
   "source": [
    "%env CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
    "%env CUDA_VISIBLE_DEVICES=0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:57.642395Z",
     "start_time": "2020-11-12T22:50:49.199690Z"
    }
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from tfumap.semisupervised_keras import pretrained_networks\n",
    "from tfumap.semisupervised_keras import load_architecture\n",
    "from tfumap.paths import MODEL_DIR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:57.652654Z",
     "start_time": "2020-11-12T22:50:57.644391Z"
    }
   },
   "outputs": [],
   "source": [
    "from tfumap.semisupervised_keras import load_dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:57.663297Z",
     "start_time": "2020-11-12T22:50:57.654238Z"
    }
   },
   "outputs": [],
   "source": [
    "dataset = \"mnist\"\n",
    "n_latent_dims = 1024"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:58.865915Z",
     "start_time": "2020-11-12T22:50:57.665818Z"
    }
   },
   "outputs": [],
   "source": [
    "(\n",
    "    X_train,\n",
    "    X_test,\n",
    "    X_labeled,\n",
    "    Y_labeled,\n",
    "    Y_masked,\n",
    "    X_valid,\n",
    "    Y_train,\n",
    "    Y_test,\n",
    "    Y_valid,\n",
    "    Y_valid_one_hot,\n",
    "    Y_labeled_one_hot,\n",
    "    num_classes,\n",
    "    dims\n",
    ") = load_dataset(dataset, 'full')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:59.782738Z",
     "start_time": "2020-11-12T22:50:58.867318Z"
    }
   },
   "outputs": [],
   "source": [
    "encoder, classifier, embedder = load_architecture(dataset, n_latent_dims)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:50:59.787468Z",
     "start_time": "2020-11-12T22:50:59.784553Z"
    }
   },
   "outputs": [],
   "source": [
    "aug_types = [\n",
    "    \"not_augmented\",\n",
    "    \"augmented\",\n",
    "    \"umap_euclidean\",\n",
    "    \"umap_learned\",\n",
    "    \"umap_augmented_learned\",\n",
    "    \"umap_euclidean_augmented\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:52:54.995195Z",
     "start_time": "2020-11-12T22:50:59.789287Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Logging before flag parsing goes to stderr.\n",
      "W1112 14:50:59.845838 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:50:59.848712 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:00.085269 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:00.089121 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:00.094338 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:00.097384 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:00.101487 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:00.104433 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:00.110726 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:00.113697 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:00.117759 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:00.120727 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:00.124795 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:00.127813 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:00.134148 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:00.137165 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:00.141238 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:00.144223 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:00.148234 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:00.151194 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.8143 +- 0.003888643851010273\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:05.647308 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:05.649327 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:05.803540 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:05.807257 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:05.811258 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:05.814023 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:05.817954 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:05.820735 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:05.827664 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:05.830515 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:05.834270 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:05.837094 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:05.840899 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:05.843736 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:05.849893 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:05.852706 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:05.856574 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:05.859274 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:05.863183 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:05.865887 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.928 +- 0.002584879107424562\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9785 +- 0.001450439588538592\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.8325 +- 0.003734216785351381\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.955 +- 0.0020730412441627884\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9779 +- 0.0014700880925985352\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:21.122730 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:21.126235 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:21.213243 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:21.217047 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:21.222039 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:21.224786 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:21.228785 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:21.232813 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:21.240845 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:21.243797 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:21.247717 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:21.250494 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:21.254407 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:21.257228 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:21.264454 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:21.267682 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:21.271579 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:21.274689 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:21.279081 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:21.282774 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9548 +- 0.0020774253295846763\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:24.010025 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:24.011837 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:24.126073 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:24.129376 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:24.133071 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:24.135643 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:24.139653 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:24.143817 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:24.153421 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:24.157505 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:24.161554 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:24.165150 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:24.170350 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:24.173106 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:24.178883 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:24.181457 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:24.185817 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:24.188333 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:24.191968 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:24.194453 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9715 +- 0.0016639636414297037\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9836 +- 0.0012700803124212263\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9557 +- 0.002057608077355841\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9805 +- 0.0013827418414150922\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9899 +- 0.0009998994949493674\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:40.749233 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:40.751491 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:40.873659 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:40.876701 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:40.881779 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:40.885159 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:40.890328 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:40.895064 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:40.901085 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:40.903892 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:40.907846 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:40.910884 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:40.915291 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:40.917885 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:40.924760 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:40.927404 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:40.931920 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:40.934839 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:40.938808 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:40.941697 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9787 +- 0.001443825127915427\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:43.856134 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:43.858795 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:43.973196 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:43.976324 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:43.980494 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:43.983277 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:43.987048 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:43.989836 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:43.995724 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:43.998407 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:44.002084 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:44.005141 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:44.009276 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:44.011907 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:44.017892 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:44.022096 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:44.025913 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:44.029199 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:44.034105 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:44.037039 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.986 +- 0.0011749042514179612\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9855 +- 0.0011953974234538067\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9788 +- 0.0014405054668414142\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9907 +- 0.0009598703037390001\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9925 +- 0.0008627716963368699\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:59.765623 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:51:59.768568 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:51:59.873228 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:51:59.876348 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:51:59.880389 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:51:59.883418 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:51:59.887513 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:51:59.890576 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:51:59.896692 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:51:59.899461 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:51:59.903146 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:51:59.905884 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:51:59.909955 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:51:59.912986 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:51:59.920349 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:51:59.923857 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:59.927912 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:51:59.930968 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:51:59.934932 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:51:59.937680 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9896 +- 0.0010144870625099168\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:03.480774 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:52:03.483301 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:52:03.613677 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:52:03.618147 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:52:03.624077 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:52:03.627684 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:52:03.632148 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:52:03.634818 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:52:03.645224 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:52:03.648523 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:52:03.652081 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:52:03.654544 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:52:03.662069 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:52:03.667797 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:52:03.674180 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:52:03.677040 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:03.680847 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:52:03.683499 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:52:03.688050 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:52:03.690624 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9905 +- 0.000970038659023443\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9895 +- 0.0010193012312363799\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9905 +- 0.000970038659023443\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9944 +- 0.0007462332075162562\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.993 +- 0.0008337265738837883\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:18.405559 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:52:18.407938 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:52:18.768829 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:52:18.772020 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:52:18.775991 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:52:18.778877 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:52:18.782864 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:52:18.785782 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:52:18.791926 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:52:18.794810 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:52:18.798807 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:52:18.802383 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:52:18.807473 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:52:18.810456 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:52:18.816590 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:52:18.819499 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:18.823462 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:52:18.826359 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:52:18.830335 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:52:18.833257 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9941 +- 0.0007658452846365252\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:22.239712 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:52:22.242336 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:52:22.380304 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:52:22.383251 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:52:22.387229 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:52:22.390182 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:52:22.394208 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:52:22.397132 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:52:22.404362 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:52:22.407242 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:52:22.411176 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:52:22.413983 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:52:22.417835 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:52:22.420624 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:52:22.426598 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:52:22.429396 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:22.433266 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:52:22.436064 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:52:22.445554 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:52:22.448516 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9939 +- 0.0007786391975748459\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9933 +- 0.0008157885755512882\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9938 +- 0.0007849560497250785\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.996 +- 0.0006311893535223801\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9951 +- 0.0006982828939620388\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:36.813911 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:52:36.816747 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:52:37.035973 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:52:37.039051 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:52:37.042642 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:52:37.045942 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:52:37.049961 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:52:37.052959 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:52:37.059038 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:52:37.064759 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:52:37.070921 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:52:37.074434 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:52:37.078634 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:52:37.082127 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:52:37.087931 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:52:37.091641 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:37.099064 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:52:37.102336 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:52:37.106348 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:52:37.109246 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9965 +- 0.0005905717568594016\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:39.861105 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1cee6d8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1d129e8>).\n",
      "W1112 14:52:39.862894 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1ce82e8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d20abe80>).\n",
      "W1112 14:52:39.998439 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1da19e8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278>).\n",
      "W1112 14:52:40.001730 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1e4c278> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fa86a0>).\n",
      "W1112 14:52:40.005674 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1fddf98> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90>).\n",
      "W1112 14:52:40.008575 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1fdda90> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1fdd978>).\n",
      "W1112 14:52:40.012522 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1af0860> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70>).\n",
      "W1112 14:52:40.015417 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1af0b70> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1af0cc0>).\n",
      "W1112 14:52:40.022593 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1c673c8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8>).\n",
      "W1112 14:52:40.025503 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1c675f8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1c67860>).\n",
      "W1112 14:52:40.029491 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d18df048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668>).\n",
      "W1112 14:52:40.032343 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d18df668> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d18df8d0>).\n",
      "W1112 14:52:40.036184 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f7e390> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0>).\n",
      "W1112 14:52:40.038942 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f7e6a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f7e908>).\n",
      "W1112 14:52:40.044962 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1eb1f60> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358>).\n",
      "W1112 14:52:40.047764 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d19f3358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d19f3390>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:52:40.051574 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d1f30e80> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240>).\n",
      "W1112 14:52:40.054308 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d1f38240> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d1f38400>).\n",
      "W1112 14:52:40.058145 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f05d202aeb8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208>).\n",
      "W1112 14:52:40.060892 139666144429888 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f05d2023208> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f05d2023400>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9963 +- 0.0006071498991188255\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9964 +- 0.0005989190262464533\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9957 +- 0.0006543324842921982\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.996 +- 0.0006311893535223802\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9967 +- 0.0005735076285456018\n"
     ]
    }
   ],
   "source": [
    "for labels_per_class in [4, 16, 64, 256, 1024, 'full']:\n",
    "    for aug_str in aug_types:\n",
    "        pretrained_weights_loc = pretrained_networks[dataset][aug_str][labels_per_class]\n",
    "        load_folder = (\n",
    "            MODEL_DIR\n",
    "            / \"semisupervised-keras\"\n",
    "            / dataset\n",
    "            / str(labels_per_class)\n",
    "            / pretrained_weights_loc\n",
    "        )\n",
    "        classifier.load_weights((load_folder / \"classifier\").as_posix())\n",
    "        encoder.load_weights((load_folder / \"encoder\").as_posix())\n",
    "        # test current acc\n",
    "        pretrained_predictions = classifier.predict(encoder.predict(X_test, verbose=True), verbose=True)\n",
    "        pretrained_predictions = np.argmax(pretrained_predictions, axis=1)\n",
    "        pretrained_acc = pretrained_predictions == Y_test\n",
    "        mean_acc = np.mean(pretrained_acc)\n",
    "        sem_acc = np.std(pretrained_acc) / np.sqrt(len(pretrained_acc))\n",
    "        np.save(load_folder / 'test_loss_SEM.npy', (mean_acc, sem_acc))\n",
    "        print('pretrained acc: {} +- {}'.format(mean_acc, sem_acc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T23:03:47.917851Z",
     "start_time": "2020-11-12T23:03:47.910522Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.9967"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mean_acc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
